### ISSUE TITLE
Fix DOM errors due to editor fields not in focus

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#302]
Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/3793#issuecomment-189059193

These errors are caused by the editor's fields not being in focus when the methods in question are called.

We should give the focus to the content field by default in such cases, or at least suppress the errors to debug status.

A common cause of this bug is the editor not being in focus on load, which is tracked in this issue: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/120.

A complete solution would involve forcing focus on load and preventing focus loss through HTML mode toggle/content deletion. In that case we can preserve errors of this type, since they'll be pointing us to new bugs.

Related issue: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/179

**Comment by aforcier** [comment]
Sub-issues:
- [x] #120 (Cursor in title field and keyboard up on new posts): https://github.com/wordpress-mobile/WordPress-Android/pull/3898
- [x] https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/314 (Cursor jumps to top right when switching from HTML to Visual mode): https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/326
- [x] https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/179 (WebView loses focus switching from HTML > visual with HW keyboard on `API<19`): same fix as #314
